@baseUrl = http://localhost:3333

@authToken = 

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Teste 1",
    "email": "teste1@teste.com.br",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "teste1@teste.com.br",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Yzc2MDhhZS0xNDM3LTRiMDQtYWZjZC1jYzI5N2JlMzY5NTEiLCJpYXQiOjE3NTg3NDQ3NDl9.imH-Pix6Q-el-Cuz-fd2sJguZPF_cHeuf9ZLYN4lu9gGn5hD8vz2ecCDccT-_U0xqKmvRFhUQ5s5YdiLouXqlW8PLI3sQHfLNjCOFfhXiFOYHQyeH_B5-lIFquXx8XaQuoZgqu5-gxi68iK4gKiN14FaJcQKqiOvb0NwSzaP64LQbklpPa3LazttTzwoM5XOlGKJQe9Vtrl-jZ_21GUPIHFgqXfESVHxV2A1CQwTlkHWchfQZilPxEY-czVwKZCF-xep8-pbTVPt1auIL-q3rxG3h92TsgHcVb8II9xGyCcH1t513Vdyh4m__imO_VHYbyuAJuKZjE03d9ngRFwnQw

{
    "title":"Nova pergunta 3",
    "content":"Conteudo da pergunta"
}

###

# @name fetch_question
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Yzc2MDhhZS0xNDM3LTRiMDQtYWZjZC1jYzI5N2JlMzY5NTEiLCJpYXQiOjE3NTg3NDM3MTZ9.S3Daa9Dcsp24P5xSAhCtStMi6tv9XK6nnluN5XoLEmr1Hvyz7v6JlGStdWuzUiUjLkTNJHZZB0bMR5xi5Zy5-d02JMrSUIlH93Y-SdE21yjVfq0bD2qpHtN0UCWs6hvAsdQMdL_ELCD_Dm5Qyy5wyKOwfvPbQ-NM9li85BWvb75zU5hcI4kYLA-cVsBbnsmvIsn7o9ikVPNk8iSsDeEMxqEaH1iR-YOUOp1Jj6l3q8AGFSwaaH7kMRO8-XOB9LAny94EATNU9RlIct6-0nAtPNoMwwJv7bRhTsJ3OzSH20g6JDjNcYVk7lGZMew2nGxlLA3Wok5TAiL8z954BBUgNg