@baseUrl = http://localhost:3333

@authToken = 

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Teste 1",
    "email": "teste1@teste.com.br",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "teste1@teste.com.br",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjMwNmM1OS1jZTI0LTQwMjQtOWY0Yy1jNWFiYmU3YTQ4MWYiLCJpYXQiOjE3NTg1NDkwNDN9.CRlEm2W0jiIHLFpu57Zfq-SP0R5n3wGyYGk_onhezejcfNC6poG_TE25291LDAmrSj4HI6wnX6nFlSjn49QLUFN63bcf11o7jRwlHcxsidFmqZiGGyEXiN1Gb1iuKWuKbDv0BcVIkNE5ReoaMEQyRcbSTl7YBAW8_CYnr0KEo5Q5ctq6Q4EhVKJlXIZ3GLJC5GlkBJa7e6OYaXGy168I93-_PhYOfCGRJOtmGrgstO6-iERIEG_7F2Xjv9yIdvT8QGxIpYoodzXMPE5UKXEuKZ9dFDsIZSRyLUls4qj-Ur_N3H4cJZHs5J0w6AZWi0U10ufW77LdRCMnTpyGFLCasg

{
    "title":"Nova pergunta 2",
    "content":"Conteudo da pergunta"
}

###

# @name create_question
GET {{baseUrl}}/questions?page=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjMwNmM1OS1jZTI0LTQwMjQtOWY0Yy1jNWFiYmU3YTQ4MWYiLCJpYXQiOjE3NTg1NDkwNDN9.CRlEm2W0jiIHLFpu57Zfq-SP0R5n3wGyYGk_onhezejcfNC6poG_TE25291LDAmrSj4HI6wnX6nFlSjn49QLUFN63bcf11o7jRwlHcxsidFmqZiGGyEXiN1Gb1iuKWuKbDv0BcVIkNE5ReoaMEQyRcbSTl7YBAW8_CYnr0KEo5Q5ctq6Q4EhVKJlXIZ3GLJC5GlkBJa7e6OYaXGy168I93-_PhYOfCGRJOtmGrgstO6-iERIEG_7F2Xjv9yIdvT8QGxIpYoodzXMPE5UKXEuKZ9dFDsIZSRyLUls4qj-Ur_N3H4cJZHs5J0w6AZWi0U10ufW77LdRCMnTpyGFLCasg