@baseUrl = http://localhost:3333

@authToken = 

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Teste 1",
    "email": "teste1@teste.com.br",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "teste1@teste.com.br",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNGZlMTEyMS02MGI0LTQ5MWQtYjE2Zi0yZTU5YjUyYjIzNTIiLCJpYXQiOjE3NTcwMTcwNTJ9.pEl-OFDMiSRIkpM0RgtbOG9hmrC045JxkmUdJ2FVNZljvkpyHe0rk5Fk2mQCI3Wsab8yX7AwZrv2ulhYhI-ElmvT20ZWtVqVT2iea_5uWWiSxxiHgsS6asm44kURRuQBbqXotXZ7eBJ3ssBnQs_jqIqmiLVfO2zpyn_78lFz4DxdKG3RT-AjiJb0OTr5K0Oox2g8r8R8kW0l5q5uhX3DO_KNuZgEUsbBLDDL1TflSVmOAkLnLM1foJ8aagsz_JbgmSvSfm3yXnsxUvaJ92xrJUDlOSTxoXCSrKYIoKYK-AHWYUks1FzWqy48ocD4nSWL1SKFqdheybi0XqUmIcUyZw

